### ISSUE TITLE
What license is this code published under?

### ISSUE THREAD

**Issue by ieugen** [rajasegar/htmx-calendar#1]
Hello,

I'm porting this code to ctmx to get familiarwith htmx. 
I would like to publish my work after and since it's heavily inspired by this code I decided to ask for your permission.
I will put a link to this project. 

And thank you for writing it.

https://github.com/whamtet/ctmx

**Comment by rajasegar** [comment]
I generally use MIT
Added the license file here
https://github.com/rajasegar/htmx-calendar/blob/main/LICENSE
